version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-roqke5dkloni"
s3_prefix = "hello-world"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=710231543414.dkr.ecr.us-east-1.amazonaws.com/helloworld20953121/helloworldfunction19d43fc4repo"]
